スクリプトのアップデートチェックを追加

diff --git a/usr/bin/serene-startdash-update-scripts b/usr/bin/serene-startdash-update-scripts
--- a/usr/bin/serene-startdash-update-scripts
+++ b/usr/bin/serene-startdash-update-scripts
@@ -49,3 +49,10 @@ rm $extract_dir/README.md
 # ダウンロードした一時ファイルを削除
 rm -f $download_path
 rm -rf $(dirname ${download_path})/serene-startdash-scripts-${VERSION_CODENAME}-${version}/
+
+if [[ -z $(ls ${extract_dir} 2> /dev/null) ]]; then
+    echo "Failed to update." >&2
+    exit 1
+else
+    exit 0
+fi
